# Generated by Django 3.2.19 on 2023-06-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('tele', models.CharField(max_length=12)),
                ('active', models.BooleanField(default=False)),
                ('adresse', models.CharField(max_length=128)),
                ('roles', models.CharField(choices=[('SAA', 'SAA'), ('medecin', 'medecin')], default='SAA', max_length=20)),
            ],
        ),
    ]
