# Generated by Django 3.2.19 on 2023-06-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='nom',
            field=models.CharField(default='Houda', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='roles',
            field=models.CharField(choices=[('SAA', 'SAA'), ('medecine', 'medecine'), ('chirurgie', 'chirurgie'), ('centreDC', 'centreDC'), ('pediaterie', 'pediaterie'), ('maternite', 'maternite'), ('imagerie', 'imagerie'), ('radiologie', 'radiologie')], default='SAA', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
