# Generated by Django 3.2.19 on 2023-06-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0002_auto_20230616_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='username',
            field=models.CharField(default='Houda', max_length=100, unique=True),
        ),
    ]
