# Generated by Django 3.2.19 on 2023-06-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0007_auto_20230616_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='nom',
            field=models.CharField(default='patien', max_length=12),
            preserve_default=False,
        ),
    ]
