# Generated by Django 3.2.19 on 2023-06-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0008_consultation_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='INPE',
            field=models.CharField(default='00000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('medecin', 'medecin'), ('personnel', 'personnel')], default='medecin', max_length=20),
        ),
    ]
