# Generated by Django 3.2.19 on 2023-06-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0010_personnel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='user',
        ),
    ]
