# Generated by Django 3.2.19 on 2023-06-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0011_remove_personnel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='serviceMedecin',
            field=models.CharField(choices=[('medecine', 'medecine'), ('chirurgie', 'chirurgie'), ('centreDC', 'centreDC'), ('pediaterie', 'pediaterie'), ('maternite', 'maternite')], default='chirurgie', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='roles',
            field=models.CharField(choices=[('SAA', 'SAA'), ('medecine', 'medecine'), ('chirurgie', 'chirurgie'), ('centreDC', 'centreDC'), ('pediaterie', 'pediaterie'), ('maternite', 'maternite'), ('biologie', 'biologie'), ('radiologie', 'radiologie')], default='SAA', max_length=20),
        ),
    ]
