# Generated by Django 3.2.19 on 2023-06-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0012_auto_20230617_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('medecin', 'medecin'), ('personnel', 'personnel')], default='SAA', max_length=20),
        ),
    ]
