# Generated by Django 3.2.19 on 2023-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0013_alter_personnel_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='serviceMedecin',
            field=models.CharField(choices=[('medecine', 'medecine'), ('chirurgie', 'chirurgie'), ('centreDC', 'centreDC'), ('pediaterie', 'pediaterie'), ('maternite', 'maternite')], default='medecine', max_length=20),
        ),
    ]
