# Generated by Django 3.2.19 on 2023-06-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0015_alter_personnel_servicemedecin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='INPE',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='active',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='serviceMedecin',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='tele',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='username',
        ),
    ]
