# Generated by Django 3.2.19 on 2023-06-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0016_auto_20230618_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personnel',
            new_name='Personne',
        ),
    ]
