# Generated by Django 3.2.19 on 2023-06-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0017_rename_personnel_personne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('nom_complet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('tele', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=100)),
                ('inpe', models.CharField(max_length=10)),
                ('responsable', models.BooleanField(default=False)),
                ('service_medecin', models.CharField(choices=[('medecine', 'Medecine'), ('chirurgie', 'Chirurgie'), ('centreDC', 'Centre de Diagnostic'), ('pediaterie', 'Pediaterie'), ('maternite', 'Maternite')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonnelSoignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('nom_complet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('tele', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=100)),
                ('service_role', models.CharField(choices=[('SAA', 'SAA'), ('medecine', 'Medecine'), ('chirurgie', 'Chirurgie'), ('centreDC', 'Centre de Diagnostic'), ('pediaterie', 'Pediaterie'), ('maternite', 'Maternite'), ('biologie', 'Biologie'), ('radiologie', 'Radiologie')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
    ]
