# Generated by Django 3.2.19 on 2023-06-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0019_auto_20230618_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='poste_role',
            field=models.CharField(choices=[('medecin', 'medecin'), ('personnel', 'personnel')], default='medecin', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnelsoignant',
            name='poste_role',
            field=models.CharField(choices=[('medecin', 'medecin'), ('personnel', 'personnel')], default='personel', max_length=20),
            preserve_default=False,
        ),
    ]
