# Generated by Django 3.2.19 on 2023-06-21 11:55

from django.db import migrations, models
import testme.models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0021_auto_20230620_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='nom',
            new_name='ipp',
        ),
        migrations.AddField(
            model_name='biologie',
            name='facture',
            field=models.FileField(default=0, upload_to='facture/', validators=[testme.models.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radio',
            name='facture',
            field=models.FileField(default=1, upload_to='facture/', validators=[testme.models.validate_file_extension]),
            preserve_default=False,
        ),
    ]
