# Generated by Django 3.2.19 on 2023-06-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0022_auto_20230621_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='poste_role',
            field=models.CharField(choices=[('medecin', 'medecin'), ('personnel', 'personnel'), ('technicien', 'technicien')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personnelsoignant',
            name='poste_role',
            field=models.CharField(choices=[('medecin', 'medecin'), ('personnel', 'personnel'), ('technicien', 'technicien')], max_length=20),
        ),
    ]
