# Generated by Django 3.2.19 on 2023-06-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0023_auto_20230621_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='poste_role',
            field=models.CharField(choices=[('medecin', 'medecin'), ('technicien', 'technicien')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personnelsoignant',
            name='poste_role',
            field=models.CharField(choices=[('medecin', 'medecin'), ('technicien', 'technicien')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personnelsoignant',
            name='service_role',
            field=models.CharField(choices=[('SAA', 'SAA')], max_length=20),
        ),
    ]
