# Generated by Django 3.2.19 on 2023-06-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0024_auto_20230622_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='service_medecin',
            field=models.CharField(choices=[('medecine', 'Medecine'), ('chirurgie', 'Chirurgie'), ('pediaterie', 'Pediaterie'), ('maternite', 'Maternite')], max_length=20),
        ),
    ]
