# Generated by Django 3.2.19 on 2023-06-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testme', '0025_alter_medecin_service_medecin'),
    ]

    operations = [
        migrations.CreateModel(
            name='authentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('poste_role', models.CharField(choices=[('medecin', 'medecin'), ('technicien', 'technicien')], max_length=20, null=True)),
            ],
        ),
    ]
